- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: docs
  color: 0075ca
  description: Documentation improvements
- name: chore
  color: cfd3d7
  description: Build, CI, refactors, maintenance
- name: good first issue
  color: 7057ff
  description: Good for newcomers
- name: help wanted
  color: 008672
  description: Extra attention is needed

# Project-specific
- name: mvp
  color: 5319e7
  description: MVP scope and acceptance
- name: qa
  color: fbca04
  description: Quality assurance and testing
- name: acceptance
  color: 0e8a16
  description: Acceptance criteria and checks
