# Web Engine Configuration for Desktop Agent
# Phase 5: Chrome Extension + Native Messaging implementation

# Engine selection: "extension" or "playwright"
engine: "extension"          # Default to new extension engine

# Playwright engine configuration (existing)
playwright:
  headless: false
  timeout: 30000
  slow_mo: 100
  viewport:
    width: 1280
    height: 720
  user_agent: "Desktop Agent WebX/1.0"
  
# Extension engine configuration (Phase 5)
extension:
  # Extension ID - set after installation
  id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  
  # Native messaging host configuration
  native_host: "com.desktopagent.webx"
  
  # Handshake token for authentication
  handshake_token: "change-me-in-production"
  
  # Request timeout in milliseconds
  timeout_ms: 15000
  
  # Enable debugger permission for file uploads (default: false for security)
  enable_debugger_upload: false
  
  # Auto-reconnect settings
  max_reconnect_attempts: 3
  reconnect_delay_ms: 5000

# Common settings for both engines
common:
  # Screenshot configuration
  screenshot:
    quality: 80
    format: "png"
    full_page: false
  
  # Download handling
  download:
    default_directory: "./downloads"
    timeout_ms: 30000
    
  # Security settings
  security:
    # Mask sensitive fields in logs
    mask_sensitive_data: true
    sensitive_patterns:
      - "password"
      - "passwd" 
      - "pwd"
      - "secret"
      - "token"
      - "key"
      - "credit"
      - "card"
      - "ccv"
      - "cvv"
      - "ssn"
      - "social"
      - "pin"
      - "otp"
    
    # Require approval for destructive actions
    require_approval_for_destructive: true
    destructive_keywords:
      - "delete"
      - "remove"
      - "cancel"
      - "unsubscribe"
      - "logout"
      - "sign out"

# Metrics and monitoring
metrics:
  # Enable metrics collection
  enabled: true
  
  # Track performance metrics
  track_performance: true
  
  # Track error rates and types
  track_errors: true
  
  # Store artifacts (screenshots, DOM schemas)
  store_artifacts: true
  artifacts_directory: "./artifacts"

# Development and debugging
development:
  # Enable verbose logging
  verbose_logging: false
  
  # Store debug artifacts
  debug_artifacts: false
  
  # Mock mode for testing
  mock_mode: false