name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright (Python)
        run: |
          python -m playwright install --with-deps chromium
      - name: Lint
        run: flake8
      - name: Run unit tests
        run: pytest tests/ -v -k "not e2e"
        env:
          PLAYWRIGHT_HEADLESS: "true"
      
  e2e-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Playwright with browsers (Python)
        run: |
          python -m playwright install --with-deps chromium
      - name: Start server
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          echo "Waiting for server to be ready..." 
          for i in {1..60}; do 
            if curl -fsS http://127.0.0.1:8000/healthz >/dev/null; then 
              echo "Server is up"; 
              break; 
            fi; 
            sleep 1; 
          done
        env:
          PLAYWRIGHT_HEADLESS: "true"
      - name: Run E2E tests
        run: pytest tests/ -v -k "e2e" --maxfail=3
        env:
          PLAYWRIGHT_HEADLESS: "true"
          BASE_URL: "http://127.0.0.1:8000"
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: |
            test-results/
            data/screenshots/
          retention-days: 7
