name: Sync Labels

on:
  push:
    branches: [ main ]
    paths:
      - .github/labels.yml
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
          dry-run: false
          skip-delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
